name: Deploy API (API Gateway + Lambda + DynamoDB)

on:
  push:
    branches: [main]
    paths:
      - "api/**"
  workflow_dispatch:

jobs:
  deploy_cdk:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.19

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm test

      - name: Install layer dependencies
        run: cd lib/layer/nodejs && npm install

      - name: Deploy CDK (API stack)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "sa-east-1"
        run: npx cdk deploy api --require-approval never
